name: Build OmniPull macOS DMG

on:
  push:
    branches:
      - macOS
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build OmniPull with PyInstaller
        run: |
          pyinstaller main.py \
            --noconfirm \
            --onefile \
            --windowed \
            --name OmniPull \
            --icon icons/logo.icns \
            --add-data "modules/translations:translations"

      - name: Create OmniPull.app manually
        run: |
          mkdir -p OmniPull.app/Contents/MacOS
          cp dist/OmniPull OmniPull.app/Contents/MacOS/OmniPull
          mv OmniPull.app dist/

      - name: List dist/ contents for verification
        run: ls -R dist/

      - name: Install create-dmg
        run: npm install -g create-dmg

      - name: Create DMG from .app
        run: |
          create-dmg \
            --volname "OmniPull" \
            --background "icons/logo4.png" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "OmniPull.app" 200 190 \
            --hide-extension "OmniPull.app" \
            --app-drop-link 600 185 \
            "dist/OmniPull.dmg" \
            "dist/"

      - name: Upload DMG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: OmniPull-dmg-${{ github.sha }}
          path: macOS/dist/OmniPull.dmg
