name: Build OmniPull macOS DMG

on:
  push:
    branches:
      - macOS
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build OmniPull with PyInstaller
        run: |
          pyinstaller main.py \
            --noconfirm \
            --onefile \
            --windowed \
            --name OmniPull \
            --icon icons/logo.icns \
            --add-data "modules/translations:translations"

      - name: Create valid OmniPull.app bundle
        run: |
          rm -rf dist/OmniPull.app
          mkdir -p dist/OmniPull.app/Contents/MacOS

          cp dist/OmniPull dist/OmniPull.app/Contents/MacOS/OmniPull

          cat <<EOF > dist/OmniPull.app/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key>
              <string>OmniPull</string>
              <key>CFBundleDisplayName</key>
              <string>OmniPull</string>
              <key>CFBundleExecutable</key>
              <string>OmniPull</string>
              <key>CFBundleIdentifier</key>
              <string>com.omnipull.app</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
          </dict>
          </plist>
          EOF





      - name: List dist/ contents for verification
        run: ls -R dist/

      - name: Install create-dmg
        run: npm install -g create-dmg

      - name: Verify app bundle structure
        run: ls -R dist/OmniPull.app

      - name: Ensure OmniPull is executable
        run: chmod +x dist/OmniPull.app/Contents/MacOS/OmniPull
        
      - name: Show contents of dist/
        run: ls -lh dist/


      - name: Create DMG from .app
        run: |
          cd dist
          ls -la  # Verify files present
          create-dmg --volname "OmniPull" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "OmniPull.app" 200 190 \
            --app-drop-link 600 185 \
            OmniPull.dmg .



      - name: Upload DMG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: OmniPull-dmg-${{ github.sha }}
          path: macOS/dist/OmniPull.dmg
